### ISSUE TITLE
Use enums for ConstraintGate

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#146]
Currently a circuit gate is a very generic structure:

```rust
pub struct CircuitGate<F: FftField> {
    /// row position in the circuit
    pub row: usize,
    /// type of the gate
    pub typ: GateType,
    /// gate wires
    pub wires: GateWires,
    /// constraints vector
    pub c: Vec<F>,
}
```

that is being used quite differently by every gate (`c` represents something different). I propose that we use an enum here:

```rust
pub enum CircuitGate<F: FftField> {
  GenericGate { selectors: { l: bool, r: bool, o: bool, c: Option<F> }, wires: ... },
  PoseidonGate { ... }
}
```

The other suggestion: do we really need a `row` field in the `CircuitGate` struct?

**Comment by mimoo** [comment]
the row field was removed
@querolita mentioned that using an enum is a bad idea (I believe because it's not practical with the coefficients field) so closing this one for now.

**Comment by querolita** [comment]
Basically the point was that a generic struct could work better for the type of uses CircuitGates are having. So we thought we could try to keep it as general as possible for outside use, but then write a few more specific mechanisms to treat gates in a more “descriptive” way inside, so it is also easier to code kimchi itself. But then this is gate-specific, so for each gatetype we can think of useful functions for them. So in some sense, we can keep it compatible with what’s currently written, and update it with new functions little by little. But then we need to make sure that the new functions are as performant as the current design, otherwise it may not be worth it. So one can think about a set of possible improvements / usecases of circuitgates to understand what useful functions one could have internally, and what implications it has in execution time / memory consumption, but perhaps in a different ticket.

**Comment by mimoo** [comment]
btw I created this issue: https://github.com/o1-labs/proof-systems/issues/271
