### ISSUE TITLE
Automatically compute number of powers of alpha

### ISSUE THREAD

**Issue by jspada** [o1-labs/proof-systems#272]
We currently manually count the number of powers of alpha and specify them then in `constraints_expr`.  It is equal to the number of constraints in the gate.  Since the Expr framework is already in position to know the number of constraints comprising a gate, we could do this automatically.

The advantages are: less error prone and less work to do.  There do not seem to be any performance implications.

David suggested passing the `alphas::Builder` type directly to the constraint functions so that they can use the number of powers of alpha they need directly and potentially report it back so that we can use it.

Related to: https://github.com/o1-labs/proof-systems/pull/216

**Comment by mimoo** [comment]
I'm wondering if the expression framework could keep track of enough information eventually, and even pre-compute powers of alpha (I believe it doesn't pre-compute them currently).

**Comment by querolita** [comment]
Oh well, I was not really trying to focus on the explicitness or implicitness of the number of gates, but rather the possibility to use the length of the vector of expressions that we were generating in any case to infer the range of the alphas (and avoid this being an input parameter to the `constraint()` function.

**Comment by mimoo** [comment]
Ah, so you can't do that directly because you need to know what offset you're using, and you need to communicate back what is the end of the range (so that the next argument can use that new offset).

Another way to implement this, is to create some sort of "pending registration" type.

```rust
    let mut pending = powers_of_alpha.register_pending(ConstraintType::Gate);
    some_gate::constraint(&mut pending);
    some_other_gate::constraint(&mut pending);
    pending.resolve();
```

the last line would figure out what was the highest range used, and store this into `powers_of_alpha`. But it's annoying as you need to create this other type, and change the way the combination work. (I think the new way I proposed in the argument PR is cleaner.)

**Comment by jspada** [comment]
I think she just omitted the offset detail.  You can just do
```rust
    let combined = index(GateType::ChaCha0) * E::combine_constraints(alpha0 .. alpha0 + cs.len(), cs)
    
    (combined, alpha0 + cs.len())
```

**Comment by mrmr1993** [comment]
Perhaps worth mentioning: reusing the powers of alpha in a disciplined way will let us use `expr::Cache` to reduce the size of the verifier circuit (which becomes a `let foo = ... in ...` via [here](https://github.com/o1-labs/proof-systems/blob/a7d861b6224c0ccb351eae9361f8b946acb99667/kimchi/src/circuits/expr.rs#L1948) and [here](https://github.com/o1-labs/proof-systems/blob/a7d861b6224c0ccb351eae9361f8b946acb99667/kimchi/src/circuits/expr.rs#L1964)).

Clearly, computing them in parallel rather than with the cache results in additional work, so e.g. using the first 9 powers of alpha results in `1 + 2 + ... + 9 = 9*(9+1)/2 = 45` multiplications. We should try to avoid that if there's a clean abstraction that allows us to do so.

**Comment by jspada** [comment]
> Ah, so you can't do that directly because you need to know what offset you're using (it might not be `0`), and you need to communicate back what is the end of the range (so that the next argument can use that new offset). The end of the range might be the `cs.len()` here, or it might be the `cs.len()` of another gate.
> 
> Another way to implement this, is to create some sort of "pending registration" type.
> 
> ```rust
>     let mut pending = powers_of_alpha.register_pending(ConstraintType::Gate);
>     some_gate::constraint(&mut pending);
>     some_other_gate::constraint(&mut pending);
>     pending.resolve();
> ```
> 
> the last line would figure out what was the highest range used, and store this into `powers_of_alpha`. But it's annoying as you need to create this other type, and change the way the combination work. (I think the new way I proposed in the argument PR is cleaner.)

Why not make the gate's `constraint()` definition oblivious to the particular powers of alpha and instead have the generic code deal with this responsibility.

For example, in `index.rs::constraints_expr(...)` do something like this

```rust
let mut φ = 0; // starting alpha exponent
for gate in gates {
    let gate_expr = gate.constraint();
    //            = α^0*c0 + ... + a^n*cn
    
    expr += Expr(α^φ) * gate_expr;
    //   += α^{0 + φ}*c0 + ... + a^{n + φ}*cn
    //      Symbolically evaluated, cheaply.
    //      N.b. alpha need to be known here,
    //      we just care about computing exponent
    //      using φ as offset.
    
    φ += gate_expr.len();
}
```
This way the gate designer doesn't need to think about the powers of alpha, as it is now the responsibility of the generic lower-level code to ensure the correct powers of alpha automatically.

The goal is separation of responsibility, so that the gate designer just creates the constraints and it's up to the proof system to decide what to do with them, e.g. apply powers of alpha or whatever strategy.

**Comment by mimoo** [comment]
it is in the PR no?
