### ISSUE TITLE
Fix pedantic lints

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#513]
run:

```
$ cargo clippy -- -W clippy::pedantic
```

and fix some of the warnings

**Comment by duguorong009** [comment]
@mimoo 
I will also take care of this issue.

**Comment by mimoo** [comment]
cool thanks : ) don't hesitate to ping me here or on twitter if you have questions.

**Comment by duguorong009** [comment]
@mimoo 
I think the following line is for creating the `cell(s)` for setting up the `prover_index(prover_key)`.
https://github.com/o1-labs/proof-systems/blob/master/circuit-construction/src/prover.rs#L175
Atm, it does have one parameter(`FnOnce`) for creating the default empty value.(like ` let v = system.var(|| panic!("fail"));`)
Can I update the `Writer::var()` trait to have no parameter?
The reason is that I think it is unnecessary.
Also, the parameter value is, in most cases, `|| panic("fail!")`.

**Comment by duguorong009** [comment]
@mimoo 
Please go for reviewing the PR #752 .
