### ISSUE TITLE
delete mina-curves

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#526]
I believe we should be able to delete the mina-curves crate and use pallas/vesta from https://github.com/arkworks-rs/curves

thanks to @mmaker for the pointer

**Comment by mrmr1993** [comment]
We use a different generator, and we're now locked into it because we use it for Mina public keys. @mimoo I recommend closing this issue.

Anybody considering taking this on nonetheless should also expect to create a PR on the Mina side that allows signatures etc. to still work after this change, and any PR to make this change will not be approved or merged until the PR against MinaProtocol/mina has been accepted.

**Comment by mimoo** [comment]
I was under the impression that we never use the generator specified in arkworks in our code, maybe I missed a place

**Comment by mimoo** [comment]
another thing, at a minimum we should move to their new way of doing this: https://github.com/arkworks-rs/curves/blob/master/pallas/src/fields/fq.rs

**Comment by jspada** [comment]
@mimoo - what precisely do you mean by "redefine the curve point there"?  Redefine the generator locally within the signer?  Are you sure the mina generator is not used anywhere else in proof systems, snarky, pickles, mina?

**Comment by mimoo** [comment]
I don’t think so but I might be wrong. Let’s just make this issue about defining things more clearly like in arkworks for now :o I just got enthusiastic about the possibility of deleting code
