### ISSUE TITLE
witness verify function should not be generic on the curve, but on the circuit field

### ISSUE THREAD

**Issue by mimoo** [o1-labs/proof-systems#797]
current signature of the witness verify function:

```rust
    pub fn verify<G: KimchiCurve<ScalarField = F>>(
        &self,
        witness: &[Vec<F>; COLUMNS],
        public: &[F],
    ) -> Result<(), GateError> {
```

ideally, this should be:

```rust
    pub fn verify<F>(
        &self,
        witness: &[Vec<F>; COLUMNS],
        public: &[F],
    ) -> Result<(), GateError> {
```

doing this would mean passing some information to the verify function needed by some of the functions underneath it.

I think it would be a good idea to create a `VerifyContext` type that could be passed here instead of passing each element needed as an argument

```rust
    pub fn verify<F>(
        &self,
        context: VerifyContext<F>,
        witness: &[Vec<F>; COLUMNS],
        public: &[F],
    ) -> Result<(), GateError> {
```

**Comment by jspada** [comment]
The witless `verify` can probably just be swapped out for `verify_witness`, which is meant to superseed it.  It currently supports verification for more gates by re-using the gate constraints themselves instead of providing a second implementation.  This reduces the amount of code we need to write and also makes debugging the actual constraints faster. 
 It also can pinpoint exactly which constraints fail.  N.b if we desire verify to also run any existing second implementation of verification for a gate, those can also be called from `verify_witness`.
